baseURL = "https://aymerictouche.fr/"
languageCode = "fr-fr"
title = "Lead Dev & Solution Architect"
theme = "hugo-coder"
defaultContentLanguage = "fr"

[params]
    author = "Aymeric Touche"
    info = "Lead Dev & Solution Architect chez RCF"
    description = "Lead Developer Fullstack & Solution Architect"
    footercontent = "Propulsé par Hugo & Cloudflare Pages"
    colorScheme = "light"

    [[params.social]]
        name = "LinkedIn"
        icon = "fa fa-linkedin"
        weight = 2
        target = '_blank'
        url = "https://www.linkedin.com/in/aymeric-touche-b7015617b/"

[[menu.main]]
    name = "Expériences"
    weight = 1
    url = "posts/experience-rcf"
[[menu.main]]
    name = "Stack"
    weight = 2
    url = "posts/tech"
[[menu.main]]
    name = "Bénévolat"
    weight = 3
    url = "posts/benevolat"
[[menu.main]]
    name = "Formation"
    weight = 4
    url = "posts/education"